version: "3.7"
services:
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
  e2e-tests:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        VARIANT: 16-buster
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    # can't be overrided in extended docker-compose.yml
    # run it with docker-compose run --rm -entrypoint=protractor
    #entrypoint: protractor
    #command: 
    #  - /app/conf.js
    volumes:
      - .:/app
